/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitalisRouteImport } from './routes/vitalis'
import { Route as StudioBellaRouteImport } from './routes/studio-bella'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as PrimeImoveisRouteImport } from './routes/prime-imoveis'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as IndexRouteImport } from './routes/index'

const VitalisRoute = VitalisRouteImport.update({
  id: '/vitalis',
  path: '/vitalis',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioBellaRoute = StudioBellaRouteImport.update({
  id: '/studio-bella',
  path: '/studio-bella',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeImoveisRoute = PrimeImoveisRouteImport.update({
  id: '/prime-imoveis',
  path: '/prime-imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/crm': typeof CrmRoute
  '/prime-imoveis': typeof PrimeImoveisRoute
  '/scheduling': typeof SchedulingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio-bella': typeof StudioBellaRoute
  '/vitalis': typeof VitalisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/crm': typeof CrmRoute
  '/prime-imoveis': typeof PrimeImoveisRoute
  '/scheduling': typeof SchedulingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio-bella': typeof StudioBellaRoute
  '/vitalis': typeof VitalisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/crm': typeof CrmRoute
  '/prime-imoveis': typeof PrimeImoveisRoute
  '/scheduling': typeof SchedulingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio-bella': typeof StudioBellaRoute
  '/vitalis': typeof VitalisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/crm'
    | '/prime-imoveis'
    | '/scheduling'
    | '/sitemap.xml'
    | '/studio-bella'
    | '/vitalis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/crm'
    | '/prime-imoveis'
    | '/scheduling'
    | '/sitemap.xml'
    | '/studio-bella'
    | '/vitalis'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/crm'
    | '/prime-imoveis'
    | '/scheduling'
    | '/sitemap.xml'
    | '/studio-bella'
    | '/vitalis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRoute
  CrmRoute: typeof CrmRoute
  PrimeImoveisRoute: typeof PrimeImoveisRoute
  SchedulingRoute: typeof SchedulingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioBellaRoute: typeof StudioBellaRoute
  VitalisRoute: typeof VitalisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitalis': {
      id: '/vitalis'
      path: '/vitalis'
      fullPath: '/vitalis'
      preLoaderRoute: typeof VitalisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-bella': {
      id: '/studio-bella'
      path: '/studio-bella'
      fullPath: '/studio-bella'
      preLoaderRoute: typeof StudioBellaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prime-imoveis': {
      id: '/prime-imoveis'
      path: '/prime-imoveis'
      fullPath: '/prime-imoveis'
      preLoaderRoute: typeof PrimeImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRoute,
  CrmRoute: CrmRoute,
  PrimeImoveisRoute: PrimeImoveisRoute,
  SchedulingRoute: SchedulingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioBellaRoute: StudioBellaRoute,
  VitalisRoute: VitalisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
